title: "Nédia Galvão"
description: "Blog, estudos bíblicos, resenhas, materiais cristãos e reflexões."
url: "https://nediagalvao.com.br"
baseurl: ""

permalink: /blog/:title/

collections:
  materiais:
    output: true
    permalink: /materiais/:title/
  conteudos:
    output: true
    permalink: /conteudos/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "materiais"
    values:
      layout: "material"

  - scope:
      path: ""
      type: "conteudos"
    values:
      layout: "conteudo"

markdown: kramdown

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .jekyll-cache
  - _site
include:
  - _headers
  - config-decap.yml